# Generated by Django 3.0.3 on 2021-02-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advactivity',
            name='name',
            field=models.CharField(default='today', max_length=128),
        ),
        migrations.AddField(
            model_name='envactivity',
            name='name',
            field=models.CharField(default='today', max_length=128),
        ),
        migrations.AddField(
            model_name='intervactivity',
            name='name',
            field=models.CharField(default='today', max_length=128),
        ),
        migrations.AddField(
            model_name='medicactivity',
            name='name',
            field=models.CharField(default='today', max_length=128),
        ),
        migrations.AddField(
            model_name='prevactivity',
            name='name',
            field=models.CharField(default='today', max_length=128),
        ),
    ]
