# Generated by Django 3.0.3 on 2021-02-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210228_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advreport',
            name='date',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='advreport',
            name='name',
            field=models.CharField(default='/', max_length=1024),
        ),
        migrations.AlterField(
            model_name='advreport',
            name='so_sc_24',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='advreport',
            name='so_sc_mtd',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='date',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='domestic_water_quality',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='incident_24',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='incident_mtd',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='incident_ytd',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='name',
            field=models.CharField(default='/', max_length=1024),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='so_sc_24',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='so_sc_mtd',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='solid_waste',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='swimming_pool',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='waste_water_quality_cpf',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='waste_water_quality_iacp',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='waste_water_quality_military',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='envreport',
            name='waste_water_quality_sarpi',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='alarms',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='date',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='etat_fire_fighting',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='etat_landrover',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='etat_others',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='etat_rescue',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='etat_silvani',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='etat_vma45',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='inspec_airstrip',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='inspec_bdv',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='inspec_cc',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='inspec_cpf',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='inspec_iacp',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='perm_jour',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='perm_nuit',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='pers_agt',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='pers_ce',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='pers_cmt',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='pers_cond',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='pers_tech',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='pers_total',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='so_sc_24',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='intervreport',
            name='so_sc_mtd',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='bdv_jour',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='bdv_nuit',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='cons_extra',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='cons_jv',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='cpf',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='date',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='doc',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='embauche_extra',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='embauche_jv',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='equip_hors_serv',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='iacp_jour',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='iacp_nuit',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='incident',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='mercedes',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='mercedes4x4',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='periodique',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='renault',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='so_sc_24',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='so_sc_mtd',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='soins_genereux',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='medicreport',
            name='toyota',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='date',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='gasdet_avail',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='gasdet_issued',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='gasdet_outofserv',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='incident_24',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='incident_mtd_all',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='incident_mtd_rec',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='incident_ytd_all',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='incident_ytd_rec',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='inspection_audit_jv',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='inspection_audit_prev',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='manpower_cds',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='manpower_eng',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='manpower_insp',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='manpower_tech',
            field=models.CharField(default='/', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='num_ptw_cpf',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='num_ptw_log',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='num_ptw_projdeb',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='num_ptw_total',
            field=models.CharField(default='/', max_length=64),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='so_sc_24_jv',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='so_sc_24_prev',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='so_sc_mtd_jv',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AlterField(
            model_name='prevreport',
            name='so_sc_mtd_prev',
            field=models.CharField(default='0', max_length=512),
        ),
    ]
